### ISSUE TITLE
Hard deleting row instead of soft delete

### ISSUE THREAD

**Issue by vaidehi-imedia** [bsiddiqui/bookshelf-paranoia#22] opened 2017-04-17 11:25 UTC
Call plugin like this
bookshelf.plugin(require('bookshelf-paranoia'), { field: 'is_delete' })

This permanently deletes row from table instead of setting is_delete flag as true.
I'm using bookshelf 0.10.3 and bookshelf-paranoia 0.10.4 version.

Thanks,
Vaidehi

**Comment by bsiddiqui** [comment] 2017-04-17 18:08
@vaidehi-imedia can you add a code sample of your model and how you're deleting the row

**Comment by bsiddiqui** [comment] 2017-04-17 19:03
Might be related to a bug fixed by https://github.com/estate/bookshelf-paranoia/pull/21

**Comment by vaidehi-imedia** [comment] 2017-04-18 06:20
I have folder called "model" inside which resides my all models.

Inside my model folder, I have one index.js file where I did my database connection and initiated bookshelf and bookshelf paranoia like this:

var bookshelf = require('bookshelf')(db.knex);
bookshelf.plugin(require('bookshelf-paranoia'));

Now, I have one model called "Role", inside  that I wrote like this:
var Role = bookself.Model.extend({
    soft: 'is_deleted',
    deleteRole: function (req) {
        return Role
            .where({
                id: req.body.role_id
            })
            .destroy({ require: true})
            .then(function then(results) {
                var Res = {
                    "statusCode": "204"
                }
                return Res;
            }).catch(function (err) {
                return Promise.reject(new errors.BadRequestError(i18n.t('errors.models.role.anErrorOccurred')));
            });
    }
});

In my role table, "is_deleted" field needs to be set as true; when I try to delete role. But its deleting from my table itself.

Can you let me know, what configurations I am doing wrong?

Thanks,
Vaidehi

**Comment by alanhoff** [comment] 2017-05-01 22:54
@vaidehi-imedia the problem is in your model instance, it should be configures like this

```javascript
var Role = bookshelf.Model.extend({
  softDelete: { field: 'is_deleted' } // instead of soft: true
})
```

I'll close this question but fell free to open it again if you need.

**Comment by vaidehi-imedia** [comment] 2017-05-02 05:39
Thanks  alanhoff. I'll try in this manner and will let you know, if I'm facing any issue

**Comment by vaidehi-imedia** [comment] 2017-05-02 06:58
Hi alanhoff,

I tried in following way:

var Role = bookself.Model.extend({
    tableName: 'roles',
    hasTimestamps: ['created_date', 'last_updated_date'],
    softDelete: { field: 'is_deleted' },
    deleteRole: function (req) {
          return Role
                    .where({
                        id: req.body.id
                    })
                    .destroy({ require: true})
                    .then(function then(results) {
                        var Res = {
                            "statusCode": "204"
                        }
                        return Res;
                    }).catch(function (err) {
                        return Promise.reject(new errors.BadRequestError(i18n.t('errors.models.role.anErrorOccurred')));
                    });
          }
    });

Still row is getting deleted from table instead of is_deleted field should be set as 1

**Comment by alanhoff** [comment] 2017-05-02 16:22
@vaidehi-imedia currently isn't possible to set the field value as a Boolean, you'll need to use it as a timestamp field.

Have you remembered to add the plugin?

```javascript
bookshelf.plugin(require('bookshelf-paranoia'))
```

**Comment by vaidehi-imedia** [comment] 2017-05-03 05:53
@alanhoff yes I have added plugin

**Comment by vaidehi-imedia** [comment] 2017-05-03 06:01
@alanhoff , can you elaborate currently isn't possible to set the field value as a Boolean, you'll need to use it as a timestamp field.?

**Comment by bsiddiqui** [comment] 2017-05-10 03:47
@vaidehi-imedia yes, the field must be a timestamp field - you can see an example in the tests: https://github.com/estate/bookshelf-paranoia/blob/master/test/db/migrations/20160415000910_sessions.js#L7

**Comment by vaidehi-imedia** [comment] 2017-05-10 05:46
@bsiddiqui, Thanks for the update. I'll try in this manner and will let you know, if I'm facing any problem

**Closed** 2018-07-19 04:01 UTC
